export const GET_CONVERSATIONS_REQUEST =  "GET_CONVERSATIONS_REQUEST";
export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS";
export const GET_CONVERSATIONS_FAIL = "GET_CONVERSATIONS_FAIL";

export const GET_CURRENT_CONVERSATION_REQUEST = "GET_CURRENT_CONVERSATION_REQUEST";
export const GET_CURRENT_CONVERSATION_SUCCESS = "GET_CURRENT_CONVERSATION_SUCCESS";
export const GET_CURRENT_CONVERSATION_FAIL = "GET_CURRENT_CONVERSATION_FAIL";
export const GET_CURRENT_CONVERSATION_NO = "GET_CURRENT_CONVERSATION_NO";

export const SET_UNREAD_MESSAGES_IN_CURRENT_CONVERSATION = "SET_UNREAD_MESSAGES_IN_CURRENT_CONVERSATION";
export const SET_IS_SCROLLING_IN_CONVERSATIONS = "SET_IS_SCROLLING_IN_CONVERSATIONS";

export const ADD_MESSAGE_TO_CURRENT_CONVERSATION = "ADD_OWN_MESSAGE_TO_CURRENT_CONVERSATION";
export const ADD_PARTNER_MESSAGE_TO_CONVERSATION = "ADD_PARTNER_MESSAGE_TO_CONVERSATION";
export const INCREMENT_UNREAD_MESSAGES_IN_CURRENT_CONVERSATION = "INCREMENT_UNREAD_MESSAGES_IN_CURRENT_CONVERSATION";

export const SEND_UPDATE_CURRENT_CONVERSATION_REQUEST = "SEND_UPDATE_CURRENT_CONVERSATION_REQUEST";
export const SEND_UPDATE_CURRENT_CONVERSATION_DONE = "SEND_UPDATE_CURRENT_CONVERSATION_DONE";
