export const GET_CONVERSATIONS_REQUEST =  "GET_CONVERSATIONS_REQUEST";
export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS";
export const GET_CONVERSATIONS_FAIL = "GET_CONVERSATIONS_FAIL";

export const GET_CURRENT_CONVERSATION_REQUEST = "GET_CURRENT_CONVERSATION_REQUEST";
export const GET_CURRENT_CONVERSATION_SUCCESS = "GET_CURRENT_CONVERSATION_SUCCESS";
export const GET_CURRENT_CONVERSATION_FAIL = "GET_CURRENT_CONVERSATION_FAIL";
export const GET_CURRENT_CONVERSATION_NO = "GET_CURRENT_CONVERSATION_NO";

export const SET_UNREAD_MESSAGES_INCONVERSATIONS = "SET_UNREAD_MESSAGES_INCONVERSATIONS";
export const SET_IS_SCROLLING_INCONVERSATIONS = "SET_IS_SCROLLING_INCONVERSATIONS";
