export const GET_CONVERSATIONS_REQUEST =  "GET_CONVERSATIONS_REQUEST";
export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS";
export const GET_CONVERSATIONS_FAIL = "GET_CONVERSATIONS_FAIL";

export const GET_CURRENT_CONVERSATION_REQUEST = "GET_CURRENT_CONVERSATION_REQUEST";
export const GET_CURRENT_CONVERSATION_SUCCESS = "GET_CURRENT_CONVERSATION_SUCCESS";
export const GET_CURRENT_CONVERSATION_FAIL = "GET_CURRENT_CONVERSATION_FAIL";
export const GET_CURRENT_CONVERSATION_NO = "GET_CURRENT_CONVERSATION_NO";

export const GET_CONVERSATION_MESSAGES_REQUEST =  "GET_CONVERSATION_MESSAGES_REQUEST";
export const GET_CONVERSATIONS_MESSAGES_SUCCESS = "GET_CONVERSATIONS_MESSAGES_SUCCESS";
export const GET_CONVERSATIONS_MESSAGES_FAIL = "GET_CONVERSATIONS_MESSAGES_FAIL";


export const SET_CURRENT_CONVERSATION = "SET_CURRENT_CONVERSATION";

