
@host=http://0.0.0.0:7000


################# Auth Route BEGIN ###################################

GET {{host}}/dev/auth 

###

POST {{host}}/auth/signup 
Content-Type: application/json

{
    "nickname": "vasyl",
    "password": "vasyl"
}

################# Auth Route BEND ###################################

################# Contact Route BEGIN ###################################

POST  {{host}}/secure/contact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6InZhc3lsIiwiX2lkIjoiNWY2ZTJjM2VmOTlmMTM3ODJlMzgwZTU2IiwiaWF0IjoxNjAxMDcwNzMzLCJleHAiOjE2MDEwNzQzMzN9.i3_Fys372-mlIivjes2sJHaM9P9dO2bkFuLpixwZYuY

{
    "nickname": "lebwa"
}


###

DELETE {{host}}/secure/contact
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6InZhc3lsIiwiX2lkIjoiNWY2ZTJjM2VmOTlmMTM3ODJlMzgwZTU2IiwiaWF0IjoxNjAxMDcwNzMzLCJleHAiOjE2MDEwNzQzMzN9.i3_Fys372-mlIivjes2sJHaM9P9dO2bkFuLpixwZYuY

{
    "nickname": "lebwa"
}

###

GET {{host}}/secure/contact 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6InZhc3lsIiwiX2lkIjoiNWY2ZTJjM2VmOTlmMTM3ODJlMzgwZTU2IiwiaWF0IjoxNjAxMDcwNzMzLCJleHAiOjE2MDEwNzQzMzN9.i3_Fys372-mlIivjes2sJHaM9P9dO2bkFuLpixwZYuY

################# Contact Route END ###################################
