
@host=http://0.0.0.0:7000

@token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6InZhc3lsIiwiX2lkIjoiNWY3NTJiMTRiOGY1NjM3ZjBlMjBkNmM0IiwiaWF0IjoxNjAyOTYyNTQ0LCJleHAiOjE2MDI5NjYxNDR9.LDUEtVANPpShoOgfXbIFn0PuDJDwi9o9EIp0d_tU81o

@name=vasyl
################# Auth Route BEGIN ###################################

GET {{host}}/dev/auth 

###

POST {{host}}/auth/signin
Content-Type: application/json

{
    "nickname": "lebwa",
    "password": "lebwa"
}

###


POST {{host}}/auth/signin
Content-Type: application/json

{
    "nickname": "vasyl",
    "password": "vasyl"
}

###

POST {{host}}/auth/signin
Content-Type: application/json

{
    "nickname": "vadum",
    "password": "vadum"
}

################# Auth Route BEND ###################################


################# Contact Route BEGIN ###################################

POST  {{host}}/secure/contact
Content-Type: application/json
Authorization: {{token}}

{
    "nickname": "lebwa"
}


###

DELETE {{host}}/secure/contact
Content-Type: application/json
Authorization: {{token}}

{
    "_id": "5f752b11b8f5637f0e20d6c3"
}

###

GET {{host}}/secure/contact
Authorization: {{token}}


################# Contact Route END ###################################


################# Conversation Route START ###################################

PUT {{host}}/secure/conversation
Content-Type: application/json
Authorization:  {{token}}

{
    "_id": "5f8b445b3357364bafc8321d",
    "conversation": {
        
	}
}

###

GET {{host}}/secure/conversation    
Authorization: {{token}}

###

DELETE {{host}}/secure/conversation
Content-Type: application/json
Authorization: {{token}}

{
    "_id": "5f752b14b8f5637f0e20d6c4"
}
################# Conversation Route END ###################################


################# Message Route START ###################################

POST {{host}}/secure/message
Content-Type: application/json
Authorization: {{token}}

{
    "_id":"5f752b11b8f5637f0e20d6c3",
    "message": "hello, lebwa !"
}


###

GET {{host}}/secure/message
Content-Type: application/json
Authorization: {{token}}

{
    "_id":"5f752b11b8f5637f0e20d6c3"
}

###

DELETE {{host}}/secure/message
Content-Type: application/json
Authorization: {{token}}

{
    "_id":"5f752b14b8f5637f0e20d6c4",
    "messageId": "5f7b562d778f30bf175d7d46"
}


################# Message Route END ###################################
