export const AUTH_SIGNIN_REQUEST = "AUTH_SIGNIN_REQUEST";
export const AUTH_SIGNIN_SUCCESS = "AUTH_SIGNIN_SUCCESS";
export const AUTH_SIGNIN_ERROR = "AUTH_SIGNIN_ERROR";

export const AUTH_SIGNUP_REQUEST = "AUTH_SIGNIN_REQUEST";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNIN_SUCCESS";
export const AUTH_SIGNUP_ERROR = "AUTH_SIGNIN_ERROR";